cluster:
  name: tarokkk-cicd

pipeline:
  build_container:
    image: plugins/docker
    repo: tarokkk/dotnet-helloworld-example
    tags: latest
    secretFrom:
      DOCKER_USERNAME:
        name: docker
        keyRef: username
      DOCKER_PASSWORD:
        name: docker
        keyRef: password