cluster:
  name: tarokkk-cicd

pipeline:
  build_container:
    image: plugins/docker
    repo: tarokkk/dotnet-helloworld-example
    tags: latest
    secretFrom:
      DOCKER_USERNAME:
        name: docker
        keyRef: username
      DOCKER_PASSWORD:
        name: docker
        keyRef: password

  package_application:
    image: lachlanevenson/k8s-helm:latest
    commands:
      - helm init -c
      - helm package ./.banzaicloud/charts/helloworld-example
  deploy_application:
    image: banzaicloud/ci-pipeline-client:0.10
    action: EnsureDeployment
    deployment:
      name: './helloworld-example-0.1.0.tgz'
      wait: true
      timeout: 900